### PR TITLE
workround for duplicate xrefs

### PR DESCRIPTION
**Pull request by edwery**
This would mask the issue - if we want to do so.

### CODE REVIEW

**Comment by mike99christie** [comment]
I'm not sure why you've added the field m.meta_key to the results and what impact that will have on the use of DISTINCT. What will/should happen to a group where the user has set both 'coordinator_ID', 'tutor_ID' to the same contact? i don't have an answer but it seems unlikely anyway!
In any case please add a one line comment on why DISTINCT is in the query, probably so say "duplicate values shouldn't exist but DISTINCT is used just in case as we only want to list each post_id once".

**Comment by edwery** [comment]
I will add a comment to the code. What needs to be distinct is a combination of the post id and the meta_key, so I included meta_key in the query. I wanted to disallow duplicate venue_ID, but allow both venue_ID and eventVenue_ID for the same post.

**Comment by edwery** [comment]
If the user has set both venue_ID and eventVenue_ID to the same venue, then there will still be a duplicated entry in the xrefs list. I had originally thought that I could not make the value unique because some lists of IDs might be from different tables - but of course they dont, so a better solution is to make the value unique - will change that.

**Comment by mike99christie** [comment]
I think this can be simpler. The only we want in the results is the ID, post_title, and post_type of the posts that are found and we don't want duplicates.
So **SELECT DISTINCT ID, post_title, post_type FROM** ....etc will do and we don't need to get confused about whether multiple metakeys gave rise to this post or not.
BTW, as it happens no post has a both venue_ID and eventVenue_ID as these metakeys relate to u3a_groups and u3a_events respectively, but even if some post could set them both to the venue that we are searching for, we only want the post once.

**Comment by edwery** [comment]
I was considering the xrefs to contacts, where you can have many different types of contact referenced. If two contacts happen to have the same title, they could be different but appear as duplicates and get filtered. Nothing stops people setting up two 'groups coordinator' entries - we have that at Romsey.

**Comment by mike99christie** [comment]
Just remember that find_xrefs is looking for refs to a single u3a_contact (or single u3a_event) post. References to other contact posts are just not looked at by the query, and so are irrelevant, even if the have the same post_title. In the SQL query are retrieving the group title not the contact/event title.
It is all confusing, since everything is a post!

**Comment by edwery** [comment]
ok, got it (eventually) :)

**Review by mike99christie — APPROVED** [review]
I'm happy with this

**Pull request merged**
